### ISSUE TITLE
Verse references incorrectly contain Strong's Numbers, Greek, etc.

### ISSUE THREAD

**Issue by tdstoff** [alphapapa/sword-to-org#9] opened 2022-02-26 13:29 UTC
Hi, thanks for this package. I especially like the export with linked verses. 

I'm experiencing a strange issue where the Bible verse(s) printed by `sworg-to-org-insert-outline` produce a ridiculously long printed text with Strong's numbers, Greek, etc. Below is the results of `M-x sword-to-org-insert-outline [RET] John 1:1-3 [RET]`. Does anyone have a clue why this would be? 

I'm on MacOS Monterey (M1) with diatheke installed via `brew install sword`. 

```
* John

** John 1

*** John 1:1

<w  savlm="strong:G1722 lemma.TR:εν" src="1">In</w> <w  savlm="strong:G746 lemma.TR:αρχη" src="2">the beginning</w> <w  savlm="strong:G2258 lemma.TR:ην" src="3">was</w> <w  savlm="strong:G3588 strong:G3056 lemma.TR:ο lemma.TR:λογος" src="4 5">the Word</w>, <w  savlm="strong:G2532 lemma.TR:και" src="6">and</w> <w  savlm="strong:G3588 strong:G3056 lemma.TR:ο lemma.TR:λογος" src="7 8">the Word</w> <w  savlm="strong:G2258 lemma.TR:ην" src="9">was</w> <w  savlm="strong:G4314 lemma.TR:προς" src="10">with</w> <w  savlm="strong:G3588 strong:G2316 lemma.TR:τον lemma.TR:θεον" src="11 12">God</w>, <w  savlm="strong:G2532 lemma.TR:και" src="13">and</w> <w  savlm="strong:G3588 strong:G3056 lemma.TR:ο lemma.TR:λογος" src="16 17">the Word</w> <w  savlm="strong:G2258 lemma.TR:ην" src="15">was</w> <w  savlm="strong:G2316 lemma.TR:θεος" src="14">God</w>.

*** John 1:2

<w  savlm="strong:G3778 lemma.TR:ουτος" src="1">The same</w> <w  savlm="strong:G2258 lemma.TR:ην" src="2">was</w> <w  savlm="strong:G1722 lemma.TR:εν" src="3">in</w> <w  savlm="strong:G746 lemma.TR:αρχη" src="4">the beginning</w> <w  savlm="strong:G4314 lemma.TR:προς" src="5">with</w> <w  savlm="strong:G3588 strong:G2316 lemma.TR:τον lemma.TR:θεον" src="6 7">God</w>.

*** John 1:3

<w  savlm="strong:G3956 lemma.TR:παντα" src="1">All things</w> <w  savlm="strong:G1096 lemma.TR:εγενετο" src="4">were made</w> <w  savlm="strong:G1223 lemma.TR:δι" src="2">by</w> <w  savlm="strong:G846 lemma.TR:αυτου" src="3">him</w>; <w  savlm="strong:G2532 lemma.TR:και" src="5">and</w> <w  savlm="strong:G5565 lemma.TR:χωρις" src="6">without</w> <w  savlm="strong:G846 lemma.TR:αυτου" src="7">him</w> <w  savlm="strong:G1096 lemma.TR:εγενετο" src="8" type="x-split-1772">was</w> <w  savlm="strong:G3761 lemma.TR:ουδε" src="9">not</w> <w  savlm="strong:G1520 lemma.TR:εν" src="10">any thing</w> <w  savlm="strong:G1096 lemma.TR:εγενετο" src="8" type="x-split-1772">made</w> <w  savlm="strong:G3739 lemma.TR:ο" src="11">that</w> <w  savlm="strong:G1096 lemma.TR:γεγονεν" src="12">was made</w>.
```

**Comment by alphapapa** [comment] 2022-03-01 09:45
Hi,

Thanks, I'm glad it's (somewhat) useful to you.

That problem probably is because of a change in `diatheke`.  The SWORD Project is not especially conservative with regard to compatibility.  What version are you using?  You might need to add some more command line options to fix the output.

**Comment by tdstoff** [comment] 2022-03-01 12:08
Here's the SWORD and `diatheke` version.
```
tdstoff ~ $ diatheke
Diatheke command-line SWORD frontend Version 4.8 (SWORD: 1.9.0)
Copyright 1999-2018 by the CrossWire Bible Society
http://www.crosswire.org/sword/diatheke/
```

**Comment by alphapapa** [comment] 2022-03-02 01:11
Ok, the version I have on this system is:
```
Diatheke command-line SWORD frontend Version 4.5
Copyright 1999-2009 by the CrossWire Bible Society
```
You might be able to find the right options in the usage output to fix it.  If you do, please let me know, and maybe I can add them here as well.

**Comment by tdstoff** [comment] 2022-08-25 13:34
@alphapapa Where did you get your SWORD distribution from? I came back to look at this again and followed the instructions [here](https://gist.github.com/Nilpo/b887da309c05845493a5) on a Mac machine and one running Ubuntu. Both `brew` and `apt` provide version 4.8 and both have this issue.

I tried building from source and going back in the commit history to what looked like pinned versions 4.5 and 4.6 but haven't got them to compile successfully yet.

I'm just a beginner in elisp but would love to dig in and try to expand on this project.

**Comment by alphapapa** [comment] 2022-08-25 21:25
> @alphapapa Where did you get your SWORD distribution from? I came back to look at this again and followed the instructions [here](https://gist.github.com/Nilpo/b887da309c05845493a5) on a Mac machine and one running Ubuntu. Both `brew` and `apt` provide version 4.8 and both have this issue.

The version that I have at the moment doesn't matter for solving this problem.

> I tried building from source and going back in the commit history to what looked like pinned versions 4.5 and 4.6 but haven't got them to compile successfully yet.

That shouldn't be necessary to solve this problem.  We need to find a solution for the the version you have and/or the latest version.

> I'm just a beginner in elisp but would love to dig in and try to expand on this project.

Thanks.  Have you tried what I suggested in my earlier responses?

**Comment by tdstoff** [comment] 2022-08-25 21:49
Good point(s), I apologize for the silly questions. You mentioned that I should try different command line options for `diatheke`, adding `-f plain` fixes it. I think this was the final conclusion of #7.

**Comment by alphapapa** [comment] 2022-09-09 18:45
@tdstoff Thanks, I'll mark this as a duplicate of that issue.

**Closed as completed by alphapapa** 2022-09-09 18:45 UTC
Labels: bug, duplicate
